package com.example.accessingdatamysql.MissonRecord;

import com.example.accessingdatamysql.Mission.MissionRepository;
import com.example.accessingdatamysql.Mission.MissionRequest;
import com.example.accessingdatamysql.Security.JwtUtil;
import com.example.accessingdatamysql.User.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class MissionRecordService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MissionRecordRepository missionRecordRepository;

    @Autowired
    private MissionRepository missionRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private JwtUtil jwtUtil;


    public String addMissionRecord(MissionRecordRequest request){
        MissionRecord n = new MissionRecord();

        String email = jwtUtil.extractEmail(request.getToken());
        Integer user_id = userRepository.findByEmail(email).getId();
        Integer mission_id = request.getMission().getId();

        n.setUserId(user_id);
        n.setMissionId(mission_id);
        n.setDate(request.getDate());

        missionRecordRepository.save(n);
        return "Saved";
    }



}
